import { stv, teqtank, posh, edx, noorda, amari } from "../assets";

export const experiences = [
  {
    title: "Fullstack Engineer",
    company_name: "Strategic Tech Ventures",
    icon: stv,
    iconBg: "#383E56",
    date: "July 2023 - Present",
    points: [
      "Led the design and development of robust software solutions, leveraging cutting-edge technologies such as React, TypeScript, GraphQL, and NextJS. This initiative contributed to a 30% improvement in system performance and a 25% reduction in time-to-market for new features.",
      "Implemented a client-centric approach, resulting in a 25% increase in client satisfaction and a 20% increase in new customer rates due to the delivery of customized applications tailored to meet the specific needs of our current clientele.",
      "Contributed to the creation of scalable and efficient software systems using CMS and AWS, leading to a 20% improvement in overall system functionality and a 15% increase in performance, resulting in heightened satisfaction for our customers.",
    ],
  },
  {
    title: "Bootcamp Instructional Specialist",
    company_name: "2U/edX",
    icon: edx,
    iconBg: "#E6DEDD",
    date: "Sept 2021 - Present",
    points: [
      "Mentored, encouraged, and supported over 250+ students across 5 different cohorts in the edX Full Stack Coding Bootcamp, offering guidance on activities, assignments, and projects, resulting in 20% improvement in overall student success rates.",
      "Collaborated with instructional staff at 2 major universities to develop and refine 24 course module objectives, create engaging class content, and provided support during over 300 hours of student office hours. This effort led to an average 10% weekly feedback increase, positively impacting instructional staff satisfaction KPIs.",
      "Delivered detailed and constructive feedback on coding projects built in JavaScript, React, SQL, PostgreSQL, MongoDB, facilitating swift identification of improvement areas and aiding in the development of strong coding skills among students.",
    ],
  },
  {
    title: "Software Developer",
    company_name: "TeqTank",
    icon: teqtank,
    iconBg: "#383E56",
    date: "July 2022 - June 2023",
    points: [
      "Implemented new client-facing features and maintained an internal software platform using Angular, TypeScript and Azure, facilitating the effective tracking of millions in weekly business revenues generated by our clients streamlining their operations and enhanced overall efficiency.",
      "Revamped the entire internal software platform styling architecture in Bootstrap and custom CSS, modernizing and streamlining UI/UX. This initiative successfully reduced over 10,000 lines of redundant and unused code, resulting in a 15% improvement in page loading times.",
      "Conceptualized and delivered web development initiatives for in-house clientele utilizing .NET, Blazor, Razor Pages and C# resulting in a 20% improvement in overall system performance on new features and a 10% reduction in bug-related issues for both the existing back-office portal and single-page applications (SPAs).",
    ],
  },
  {
    title: "Software Developer",
    company_name: "Perfectly Posh",
    icon: posh,
    iconBg: "#E6DEDD",
    date: "Jan 2023 - July 2023",
    points: [
      "Successfully developed over 16 new data visualizations for the internal consultant portal using React and PHP, resulting in a 25% enhancement in overall system functionality and a significant improvement in user experience, performance, and reliability.",
      "Collaborated with cross-functional teams to create 25+ internal and customer-facing features in React combined with Salesforce yielding a substantial 10% increase in quarterly revenue.",
      "Conducted comprehensive peer code reviews, adhering to coding standards, best practices, and test cases, resulting in a 20% increase in successful integrations and enhanced code quality, readability, and maintainability of code deployed to production environments.",
    ],
  },
  {
    title: "Fullstack Developer",
    company_name: "Noorda College of Osteopathic Medicine",
    icon: noorda,
    iconBg: "#E6DEDD",
    date: "Oct 2021 - May 2022",
    points: [
      "Engineered a fullstack decentralized research platform using React, Express, Node, and MongoDB, incorporating authentication, file and image handling, user connections, and real-time messaging. Delivered a high-performing, scalable, and secure application meticulously tailored to meet the specific needs of the Research Department.",
      "Utilized Adobe XD to streamline the development process, reducing project-to-production times by 40% and enabling the team to iterate React components rapidly on designs, ultimately expediting database integration time.",
    ],
  },
  {
    title: "Web Developer",
    company_name: "Amari Consulting",
    icon: amari,
    iconBg: "#E6DEDD",
    date: "June 2016 - June 2017",
    points: [
      "Spearheaded the development of frontend web designs for 15+ client websites using WordPress, achieving a remarkable 30% enhancement in website SEO and a substantial 20% upswing in overall user engagement, evidenced by analytic results.",
      "Directed a comprehensive redesign in FIGMA of the Amari website, creating over 20 visually captivating Adobe Photoshop/ Illustrator designs that resulted in a 25% increase in user engagement and a notable improvement in UI/UX.",
    ],
  },
];
